apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: openshift-apiserver
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
    - name: openshift-apiserver
      version: "0.0.1-snapshot"
