apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: openshift-apiserver-pdb
  namespace: openshift-apiserver
spec:
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow
  selector:
    matchLabels:
      app: openshift-apiserver-a
      apiserver: "true"
